# 4.Multivariate Linear Regression

In [50]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [51]:
torch.manual_seed(1)

In [52]:
#feature가 3개인 방식은 단순선형회귀로는 불가능
#독립변수가 여러개일 때는, 다중선형회귀 사용
#총 5명의 사람의 성적데이터(feature3개) => 각 사람의 기말고사 성적을 예측함
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

### 적접 hypothesis = x1*w1 + x2*w2 + x3*w3 + .......xn*wn + b형태로 작성하면, 독립변수가 많을 때 힘듬

In [53]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)

b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w1,w2,w3,b], lr=1e-5)

nb_epochs = 1000

for epoch in range(nb_epochs+1):
    hypothesis = x1_train*w1 + x2_train*w2 + x3_train*w3 + b

    cost = torch.mean((hypothesis-y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, w1.item(), w3.item(), w3.item(), b.item(), cost.item()))

Epoch    0/1000 w1: 0.294 w2: 0.297 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.676 w3: 0.676 b: 0.008 Cost: 1.563634
Epoch  200/1000 w1: 0.679 w2: 0.677 w3: 0.677 b: 0.008 Cost: 1.497607
Epoch  300/1000 w1: 0.684 w2: 0.677 w3: 0.677 b: 0.008 Cost: 1.435026
Epoch  400/1000 w1: 0.689 w2: 0.678 w3: 0.678 b: 0.008 Cost: 1.375730
Epoch  500/1000 w1: 0.694 w2: 0.678 w3: 0.678 b: 0.009 Cost: 1.319511
Epoch  600/1000 w1: 0.699 w2: 0.679 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.679 w3: 0.679 b: 0.009 Cost: 1.215696
Epoch  800/1000 w1: 0.709 w2: 0.679 w3: 0.679 b: 0.009 Cost: 1.167818
Epoch  900/1000 w1: 0.713 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.079378


### 직접 hypothessis를 작성하지 않고 행렬곱을 이용해서 적용

In [54]:
x_train = torch.hstack([x1_train,x2_train,x3_train])
x_train

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])

In [55]:
torch.zeros((3,1), requires_grad=True)

tensor([[0.],
        [0.],
        [0.]], requires_grad=True)

In [56]:
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=1e-5)

for epoch in range(nb_epochs+1):

    #x_train x W를 행렬곱으로 표현하면 길게 작성할 필요 없음
    hypothesis = x_train.matmul(W) + b

    cost = torch.mean((hypothesis-y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, w1.item(), w3.item(), w3.item(), b.item(), cost.item()))

Epoch    0/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.008 Cost: 1.563634
Epoch  200/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.008 Cost: 1.497607
Epoch  300/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.008 Cost: 1.435026
Epoch  400/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.008 Cost: 1.375730
Epoch  500/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.319511
Epoch  600/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.215696
Epoch  800/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.167818
Epoch  900/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.680 w3: 0.680 b: 0.009 Cost: 1.079378


### nn.Module를 이용해서 다중선형회귀 모델 구현

In [57]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)

    def forward(self , x):
        return self.linear(x)

In [58]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

In [59]:
model = MultivariateLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs=20
for epoch in range(nb_epochs):

    #5명의 사람의 기말고사 성적예측데이터
    prediction = model(x_train)

    cost = F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))
    

Epoch    0/20 Cost: 31667.599609
Epoch    1/20 Cost: 9926.266602
Epoch    2/20 Cost: 3111.513916
Epoch    3/20 Cost: 975.451355
Epoch    4/20 Cost: 305.908539
Epoch    5/20 Cost: 96.042496
Epoch    6/20 Cost: 30.260748
Epoch    7/20 Cost: 9.641701
Epoch    8/20 Cost: 3.178671
Epoch    9/20 Cost: 1.152871
Epoch   10/20 Cost: 0.517863
Epoch   11/20 Cost: 0.318801
Epoch   12/20 Cost: 0.256388
Epoch   13/20 Cost: 0.236821
Epoch   14/20 Cost: 0.230660
Epoch   15/20 Cost: 0.228719
Epoch   16/20 Cost: 0.228095
Epoch   17/20 Cost: 0.227880
Epoch   18/20 Cost: 0.227799
Epoch   19/20 Cost: 0.227762


## Loading Data => 왜 DataSet과 DataLoader를 사용하는지 모르겠음 <= 데이터를 나누는 작업을 하는 이유는 알음(속도, 과적합등) 그런데 아래 batch만큼 나눴는데, 어디서 티가 나는거지??????

##### Minibatch Gradient Descent
##### 전체 데이터를 균일하게 나눠서 학습하자(가금 잘못된 방향으로 업데이트 할 수도 있음)
1. 사용자 정의 데이터 셋 만들기 => 하나의 샘플(객체)에 feature-label를 지정함
2. minibatch를 이용해서 데이터를 섞음 => 미니배치로 전달, epoch마다 다시 섞어서 과적합을 방지함
3. 해당 객체를 이용해서 분석

In [60]:
#pytorch dataset만들기
#직접 상속받아 커스텀 데이터셋을 만듬
#Dataset클래스는 3개 함수를 구현해야함 => __init__ , __len__ , __getitem__
from torch.utils.data import Dataset

#Dataset상속
class CustomDataSet(Dataset):

    #객체를 생성할 때 실행되는 함수로 feature과 label를 설정함
    def __init__(self):
        self.x_data = x_train
        self.y_data = y_train

    #데이터 샘플 개수 반환
    def __len__(self):
        return len(self.x_data)

    #해당 인덱스idx에 대응하는 데이터 반환
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
       
        return x,y

dataset = CustomDataSet()
list(dataset)

[(tensor([73., 80., 75.]), tensor([152.])),
 (tensor([93., 88., 93.]), tensor([185.])),
 (tensor([89., 91., 90.]), tensor([180.])),
 (tensor([ 96.,  98., 100.]), tensor([196.])),
 (tensor([73., 66., 70.]), tensor([142.]))]

In [61]:
len(dataset)

5

In [62]:
dataset[1:2]

(tensor([[93., 88., 93.]]), tensor([[185.]]))

In [63]:
from torch.utils.data import DataLoader

#minibactch의 크기(2의 제곱수로 설정)
#shuffle 각 epoch마다 데이터셋을 다시 섞음(모델이 순서를 외우지 않도록) => 전체데이터개수=5 / batch_size=2 = 2.5이면 총 3번의 iteration을 수행하게 됨
#이렇게 작은 단위로 데이터셋을 나눠서 분석하는 방식을 minibatch라고 함
dataloader = DataLoader( dataset , batch_size=2, shuffle=True)

In [64]:
#batch_size를 2로 설정하면 5/2=2.5=3개로 batch를 나눔
#batch_size를 3로 설정하면 5/3=1.6=2개로 batch를 나눔
list(dataloader)

[[tensor([[73., 66., 70.],
          [73., 80., 75.]]),
  tensor([[142.],
          [152.]])],
 [tensor([[ 89.,  91.,  90.],
          [ 96.,  98., 100.]]),
  tensor([[180.],
          [196.]])],
 [tensor([[93., 88., 93.]]), tensor([[185.]])]]

In [65]:
nb_epochs = 20

for epoch in range(nb_epochs+1):
    for batch_idx , samples in enumerate(dataloader):
        x_train, y_train = samples
      
        prediction = model(x_train)

        cost = F.mse_loss(prediction,y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print("Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}".format(epoch,nb_epochs,batch_idx+1, len(dataloader), cost.item()))


Epoch    0/20 Batch 1/3 Cost: 0.444082
Epoch    0/20 Batch 2/3 Cost: 0.184806
Epoch    0/20 Batch 3/3 Cost: 0.035042
Epoch    1/20 Batch 1/3 Cost: 0.131975
Epoch    1/20 Batch 2/3 Cost: 0.508313
Epoch    1/20 Batch 3/3 Cost: 0.005707
Epoch    2/20 Batch 1/3 Cost: 0.415352
Epoch    2/20 Batch 2/3 Cost: 0.020756
Epoch    2/20 Batch 3/3 Cost: 0.337660
Epoch    3/20 Batch 1/3 Cost: 0.548951
Epoch    3/20 Batch 2/3 Cost: 0.196130
Epoch    3/20 Batch 3/3 Cost: 0.086799
Epoch    4/20 Batch 1/3 Cost: 0.103543
Epoch    4/20 Batch 2/3 Cost: 0.529867
Epoch    4/20 Batch 3/3 Cost: 0.008752
Epoch    5/20 Batch 1/3 Cost: 0.220369
Epoch    5/20 Batch 2/3 Cost: 0.040563
Epoch    5/20 Batch 3/3 Cost: 0.932337
Epoch    6/20 Batch 1/3 Cost: 0.218245
Epoch    6/20 Batch 2/3 Cost: 0.640859
Epoch    6/20 Batch 3/3 Cost: 0.006037
Epoch    7/20 Batch 1/3 Cost: 0.461589
Epoch    7/20 Batch 2/3 Cost: 0.011903
Epoch    7/20 Batch 3/3 Cost: 0.294716
Epoch    8/20 Batch 1/3 Cost: 0.567194
Epoch    8/20 Batch 2/3 C

In [66]:
_

[[tensor([[73., 66., 70.],
          [73., 80., 75.]]),
  tensor([[142.],
          [152.]])],
 [tensor([[ 89.,  91.,  90.],
          [ 96.,  98., 100.]]),
  tensor([[180.],
          [196.]])],
 [tensor([[93., 88., 93.]]), tensor([[185.]])]]