# 딥러닝을 위한 시즌2
## -Tensor Manipulation1
### 1차원(vector). 2차원(matrix), 3차원(Tensor)

- 2D Tensor(Typical Simple Setting)
|t| = (batch size, dim) 64x256 => batch size x dim

- 3D Tensor(Typical Computer Vision)
|t| = (batch size, width, height) => batch size(세로) x width(가로) x height(깊이)

- 3D Tensor(Typical Natural Language Processing)
|t| = (batch size, width, height) => batch size(세로) x width(가로) x dim => 하나의 batch에 있는 width x dim이 문장단위

In [2]:
import numpy as np
import torch

### Numpy 복습

In [3]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [4]:
#ndim : 1차원(vector)
#shape : 1차원 내 형태
t.ndim, t.shape

(1, (7,))

In [5]:
t[0],t[-1], t[2:5], t[4:-1], t[:2]

(0.0, 6.0, array([2., 3., 4.]), array([4., 5.]), array([0., 1.]))

In [6]:
t = np.array([ [1,2,3], [4,5,6], [7,8,9], [10,11,12]])
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
t.ndim, t.shape

(2, (4, 3))

### Pytorch 

In [8]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [9]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [10]:
t = torch.FloatTensor([ [1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [11]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[:,[1,2]])
print(t[:,[1,2]].size())
print(t[:,:-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([[ 2.,  3.],
        [ 5.,  6.],
        [ 8.,  9.],
        [11., 12.]])
torch.Size([4, 2])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [12]:
m1 = torch.FloatTensor([ [3,3]])
m2 = torch.FloatTensor([ [2, 4]])
m1, m2

(tensor([[3., 3.]]), tensor([[2., 4.]]))

In [13]:
m1+m2

tensor([[5., 7.]])

In [14]:
m1 = torch.FloatTensor([ [1,2]])
m2 = torch.FloatTensor([ [3]])
m1+m2

tensor([[4., 5.]])

In [15]:
#[1 2] + [3 ] = [1 2] + [3 3]
#[   ] + [4 ] = [1 2] + [4 4]
m1 = torch.FloatTensor([ [1,2]])
m2 = torch.FloatTensor([ [3], [4]])
m1+m2

tensor([[4., 5.],
        [5., 6.]])

In [16]:
#일반적인 곱셈(m1*m2, m1.mul(m2))는 BroadCasting를 이용해서 곱셈을 수행함
m1 = torch.FloatTensor([ [1,2], [3,4]])
m2 = torch.FloatTensor([ [1], [2]])

print(m1.shape)
print(m2.shape)
m1*m2

torch.Size([2, 2])
torch.Size([2, 1])


tensor([[1., 2.],
        [6., 8.]])

In [17]:
m1.mul(m2)

tensor([[1., 2.],
        [6., 8.]])

### Matrix Multiplicatio

In [18]:
m1 = torch.FloatTensor([ [1,2], [3,4]])
m2 = torch.FloatTensor([ [1], [2]])

#2x2 행렬곱 2x1 => 2x1
print(m1.shape)
print(m2.shape)

m1.matmul(m2)

torch.Size([2, 2])
torch.Size([2, 1])


tensor([[ 5.],
        [11.]])

### Mean

In [19]:
t = torch.FloatTensor([1,2])
t.mean()

tensor(1.5000)

In [20]:
#long타입은 집계함수 연산 불가능
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [21]:
t = torch.FloatTensor([ [1,2], [3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [22]:
#dim=0 : [? ?]차원으로 줄여서 mean를 구하겠다 [1 2] => [1,3의 평균, 2,4의 평균]
#                                           [3,4] 

#dim=1 : [?]차원으로 줄여서 mean를 구하겠다 [1 2] => [1,2의 평균]
#        [?]                              [3,4] => [3,4의 평균]
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [23]:
t = torch.FloatTensor([ [1,2], [3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [24]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax(max의 인덱스값)

In [25]:
t = torch.FloatTensor([ [3,2], [1,4]])
t

tensor([[3., 2.],
        [1., 4.]])

In [26]:
t.max()

tensor(4.)

In [27]:
#dim=0일 때는, ArgMax까지 반환해줌
t.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([0, 1]))

In [28]:
print(t.max(dim=0)[0])
print(t.max(dim=0)[1])

tensor([3., 4.])
tensor([0, 1])


In [29]:
print(t.max(dim=1)[0])
print(t.max(dim=1)[1])

tensor([3., 4.])
tensor([0, 1])


## -Tensor Manipulation2

### view(Numpy의 reshape기능)

In [30]:
t = np.array([ [ [0,1,2],[3,4,5]],
                  
                    [ [6,7,8], [9,10,11]]
                    ])
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [31]:
ft = torch.FloatTensor(t)
ft, ft.shape

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]]),
 torch.Size([2, 2, 3]))

In [32]:
ft.view([-1,3]), ft.view([-1,3]).shape

(tensor([[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]),
 torch.Size([4, 3]))

In [33]:
ft.view([-1,1,3]), ft.view([-1,1,3]).shape

(tensor([[[ 0.,  1.,  2.]],
 
         [[ 3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.]],
 
         [[ 9., 10., 11.]]]),
 torch.Size([4, 1, 3]))

### Squeeze
##### 불필요한 차원 줄이기 (4,1) => ft.squeeze(dim=1) => (4)
##### dim=0이면 앞에차원이 불필요한 여부를 dim=1이면 뒤에 차원이 불필요한 여부를 조사함, dim=1이면 마지막 차원이 불필요한 여부를

In [34]:
ft = torch.FloatTensor([ [0], [1], [2]])
ft, ft.shape

(tensor([[0.],
         [1.],
         [2.]]),
 torch.Size([3, 1]))

In [35]:
ft.squeeze(), ft.squeeze().shape

(tensor([0., 1., 2.]), torch.Size([3]))

In [36]:
#dim=0이면 3은 불필요한 차원이 아니므로 줄여지지 않음
#dim=1이면 1은 불필요한 차원이므로 줄임
ft.squeeze(dim=0),ft.squeeze(dim=1)

(tensor([[0.],
         [1.],
         [2.]]),
 tensor([0., 1., 2.]))

In [37]:
ft = torch.FloatTensor([ [[0, 1, 2] , [4,5,6] ]])
ft, ft.shape

(tensor([[[0., 1., 2.],
          [4., 5., 6.]]]),
 torch.Size([1, 2, 3]))

In [38]:
#dim=0이면 1은 불필요한 차원이므로 줄임
#dim=1이면 2,3은 불필요한 차원이 아니므로 줄이지 않음
ft.squeeze(dim=0),ft.squeeze(dim=1)

(tensor([[0., 1., 2.],
         [4., 5., 6.]]),
 tensor([[[0., 1., 2.],
          [4., 5., 6.]]]))

### Unsqueeze 

##### 차원을 추가해줌(dim의 원리는 같음)

In [39]:
ft = torch.Tensor([0,1,2])
ft.shape

torch.Size([3])

In [40]:
ft.unsqueeze(0), ft.unsqueeze(0).shape

(tensor([[0., 1., 2.]]), torch.Size([1, 3]))

In [41]:
ft.unsqueeze(1), ft.unsqueeze(1).shape

(tensor([[0.],
         [1.],
         [2.]]),
 torch.Size([3, 1]))

In [42]:
ft.unsqueeze(-1), ft.unsqueeze(-1).shape

(tensor([[0.],
         [1.],
         [2.]]),
 torch.Size([3, 1]))

In [43]:
ft.view(1,-1), ft.view(1,-1).shape

(tensor([[0., 1., 2.]]), torch.Size([1, 3]))

### Type Casting
##### 데이터 타입을 설정함

In [44]:
lt = torch.LongTensor([1,2,3,4])
lt

tensor([1, 2, 3, 4])

In [45]:
lt.float()

tensor([1., 2., 3., 4.])

In [46]:
bt = torch.ByteTensor([True,False,False,True])
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [47]:
bt.long(), bt.float()

(tensor([1, 0, 0, 1]), tensor([1., 0., 0., 1.]))

In [48]:
bt = (lt==3)
print(bt)

tensor([False, False,  True, False])


### Cat(Numpy의 Concatenate)
##### dim=0이면 행으로 합쳐짐, dim=1이면 열로 합쳐짐

In [49]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
x,y

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[5., 6.],
         [7., 8.]]))

In [50]:
torch.cat([x,y])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [51]:
torch.cat([x,y],dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [52]:
torch.cat([x,y],dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

### Stacking
##### x,y,x를 dim=0으로 stacking하면 x 로 쌓음
                                    y
                                    z
##### dim=1dmfh stackinggkaus x y z로 쌓음

In [53]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
x,y,z

(tensor([1., 4.]), tensor([2., 5.]), tensor([3., 6.]))

In [54]:
torch.stack([x,y,z]), torch.stack([x,y,z],dim=0)

(tensor([[1., 4.],
         [2., 5.],
         [3., 6.]]),
 tensor([[1., 4.],
         [2., 5.],
         [3., 6.]]))

In [55]:
torch.stack([x,y,z], dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [56]:
torch.cat([x,y,z])

tensor([1., 4., 2., 5., 3., 6.])

In [57]:
torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

### Ones and Zeros Like
##### 주어진 shape형식과 똑같이 만듬(imputation은 지정)

In [58]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [59]:
torch.ones_like(x), torch.zeros_like(x)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

### In-place Operation
##### 실제 객체값을 변형시킬것인지 여부

In [60]:
x = torch.FloatTensor([[1, 2], [3, 4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [62]:
x.mul(2.), x


(tensor([[ 4.,  8.],
         [12., 16.]]),
 tensor([[2., 4.],
         [6., 8.]]))

In [63]:
x.mul_(2.),x

(tensor([[ 4.,  8.],
         [12., 16.]]),
 tensor([[ 4.,  8.],
         [12., 16.]]))

In [64]:
for x,y,z in zip([1,2,3], [4,5,6], [7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
